language: python
python:
  - "2.6"
  - "2.7"

env:
  - DJANGO="Django==1.2"
  - DJANGO="Django==1.3"
  - DJANGO="Django==1.4.15"

install: pip install $DJANGO --use-mirrors

script: django-admin.py test --pythonpath=src/ --settings=shorturls.testsettings
