language: python
sudo: false
python:
  - "2.7"

env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"

install: pip install $DJANGO --use-mirrors

script: script/test

